# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "http://localhost:4321"

[_.globalMeta]
title = "devnguy"
description = "Devin Nguyen's personal portfolio and blog."
longDescription = "I'm a software engineer and neovim enthusiast, currently exploring game development."
cardImage = "https://devnguy.com/card-image.jpg"
keywords = [
  "web development",
  "software engineer",
  "design",
  "technology",
  "typescript",
  "react",
]

[_.blogMeta]
title = "devnguy blog"
description = "Guides, neovim, and ponderings"
longDescription = "Web development, tech trends, and the occasional programming mishap."
cardImage = "https://devnguy.com/card-image.jpg"
keywords = [
  "web development",
  "software engineer",
  "design",
  "technology",
  "typescript",
  "react",
]

[_.projectMeta]
title = "devnguy projects"
description = "A list of my web development projects and developer tools."
longDescription = "All of my projects, including both frontend and full-stack applications."
cardImage = "https://devnguy.com/card-image.jpg"
keywords = [
  "web development",
  "software engineer",
  "design",
  "technology",
  "typescript",
  "react",
]

[_.notFoundMeta]
title = "devnguy 404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist."
cardImage = "https://devnguy.com/card-image.jpg"

[_.hero]
title = "Devin Nguyen"
subtitle = "Software Engineer"
image = "http://localhost:4321/pfp.jpeg"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "devnguy"
githubProfile = "https://github.com/devnguy"
twitterProfile = "https://twitter.com"
linkedinProfile = "https://linkedin.com/"

[_.texts]
blogName = "Blog"
experienceName = "Experience"
projectsName = "Projects"
viewAll = "View All"
noPosts = "No posts found."
noProjects = "No projects found."

[_.menu]
home = "/"
blog = "/blog"
projects = "/projects"
experience = "/experience"
